apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plexserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plexserver
  template:
    metadata:
      labels:
        app: plexserver
    spec:
      volumes:
      - name: "media-pv"
        persistentVolumeClaim:
          claimName: "media-pvc"
      - name: "iscsi-pv"
        persistentVolumeClaim:
          claimName: "iscsi-pvc"
      containers:
      - name: plex
        image: docker.io/linuxserver/plex:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 2
            memory: 4096Mi
        ports:
        - containerPort: 32400 #PMS
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469 #Plex DLNA
          name: plex-dlna
        - containerPort: 5353
          name: plex-discovery
          protocol: UDP
        - containerPort: 1900 #Plex DLNA
          name: plex-dlna-udp
          protocol: UDP
        env:
        - name: UID
          value: "\x31\x30\x30\x33" #Corresponds to user id on NFS server (ascii)
        - name: GID
          value: "\x31\x30\x30\x33" #Corresponds to group id on NFS server
        - name: PLEX_CLAIM
          value: claim-584m4xQNz912PZi2VzfT
        - name: TZ
          value: America/New_York
        volumeMounts:
        - mountPath: /config
          subPath: configs/plex
          name: iscsi-pv
        - mountPath: /data
          subPath: configs/plex
          name: iscsi-pv

---
kind: Service
apiVersion: v1
metadata:
  name: plex-udp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver # annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
spec:
  selector:
    app: plexserver
  ports:
  - port: 1900
    targetPort: 1900
    name: dlna-udp
    protocol: UDP
  - port: 5353
    targetPort: 5353
    name: discovery-udp
    protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.175.10
---
kind: Service
apiVersion: v1
metadata:
  name: plex-tcp
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: plexserver
spec:
  selector:
    app: plexserver
  ports:                      
  - port: 32400
    targetPort: 32400
    name: pms-web
    protocol: TCP
  - port: 32469
    targetPort: 32469
    name: dlna-tcp
    protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.175.10