- name: Install prom via helm
  hosts: k8s-proxy
  become: true

  tasks:

    - name: Copy monitoring_ingress.yml to k8s-proxy
      copy:
        src: monitoring_ingress.yml
        dest: /opt/application_manifests/monitoring/monitoring_ingress.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Add prometheus helm repo
      ansible.builtin.shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update

    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        kubeconfig: /home/ansible/.kube/config

    - name: Add prometheus ingress
      ansible.builtin.shell: |
        kubectl apply --kubeconfig=/home/ansible/.kube/config -f /opt/application_manifests/monitoring/monitoring_ingress.yml
