- name: Install prom via helm
  hosts: k8s-proxy
  become: true

  tasks:

    - name: Copy values.yml to k8s-proxy
      copy:
        src: values.yml
        dest: /opt/application_manifests/monitoring/values.yml
        owner: ansible
        group: ansible
        mode: '0644'

# Uncomment below if changes were made to values.yml file

    - name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        kubeconfig: /home/ansible/.kube/config
        state: present  # Ensures the release is installed/upgraded
        values_files:
          - /opt/application_manifests/monitoring/values.yml