- name: Deploy cloudflared
  hosts: k8s-proxy
  become: yes

  tasks:

    - name: Copy cloudflare.yml to k8s-proxy
      copy:
        src: cloudflare.yml
        dest: /opt/application_manifests/cloudflare.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Copy cloudflare.yml to k8s-proxy
      copy:
        src: cloudflare.yml
        dest: /opt/application_manifests/cloudflare.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Install cloudflare
      ansible.builtin.shell: |
        kubectl apply --kubeconfig=/home/ansible/.kube/config /opt/application_manifests/cloudflare.yml
      register: res
      changed_when: res.rc != 0