---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-deployment
  namespace: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: docker.io/homeassistant/home-assistant:latest
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              subPath: configs/home-assistant-data
              name: homme-ass-pv
      volumes:
        - name: homme-ass-pv
          persistentVolumeClaim:
            claimName: home-assistant-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant-service
  namespace: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8123
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-ass-ingress
  namespace: home-assistant
spec:
  ingressClassName: nginx
  rules:
  - host: ha.cv-labs.net
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home-ass-service
            port:
              number: 80