---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "homme-ass-pv"
  labels:
    type: "local"
spec:
  storageClassName: "nfs"
  capacity:
    storage: "500Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/home-assistant"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "home-assistant"
  name: "home-assistant-pvc"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Gi"
---