services:
  nessus-essentials:
    image: tenable/nessus:latest-ubuntu # Or specify a specific version like 10.6.1-ubuntu
    container_name: nessus-essentials
    ports:
      - "8834:8834"
    restart: unless-stopped
    networks:
      - services_network

networks:
  services_network:
    external: true

