- name: Label worker nodes
  hosts: pd-k8s-workers
  become: yes

  tasks:

    - name: Configure enX2 interface
      lineinfile:
        path: /etc/network/interfaces
        line: "{{ item }}"
        insertafter: EOF
      loop:
        - "auto enX2"
        - "iface enX2 inet static"
        - "address {{ enX2_iscsi_ip }}"
        - "netmask 255.255.255.0"
    