- name: Kubernetes Dependencies
  hosts: pd-k8s
  become: yes
  vars:
    kubernetes_major_version: "1.32"
    kubernetes_release: "1.32.2-1.1"
    containerd_version: "1.7.25-1"

  tasks:

    - name: Updates
      apt:
        update_cache: yes

    - name: Reboot
      reboot:

    - name: Disable SWAP
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # Forwarding of IPv4 traffic and allowing iptables to see bridged traffic is required. Execute the following commands to enable this:

    - name: Create an empty file for the containerd module
      copy:
        content: ""
        dest: /etc/modules-load.d/k8s.conf
        force: no

    - name: Configure modules for containerd
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter

    # sysctl params required by setup, params persist across reboots

    - name: Create an empty file for K8S sysctl parameters
      copy:
        content: ""
        dest: /etc/sysctl.d/k8s.conf
        force: no

    - name: Configure sysctl parameters for K8S
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.ipv4.ip_forward                 = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl parameters
      command: sysctl --system

    - name: Install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: Add Docker apt-key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker-apt-keyring.asc
        mode: "0644"
        force: true

    - name: Add Docker's APT repository
      apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }} signed-by=/etc/apt/keyrings/docker-apt-keyring.asc] https://download.docker.com/linux/debian bookworm stable"
        state: present
        update_cache: yes

    - name: Add Kubernetes APT key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"
        force: true

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/ /"
        state: present
        update_cache: yes

    - name: Install containerd
      apt:
        name: "containerd.io={{ containerd_version }}"
        state: present

    - name: Create containerd directory
      file:
        path: /etc/containerd
        state: directory

    - name: Add containerd configuration
      shell: /usr/bin/containerd config default > /etc/containerd/config.toml

    - name: Configuring Systemd cgroup driver for containerd
      lineinfile:
        path: /etc/containerd/config.toml
        regexp: "            SystemdCgroup = false"
        line: "            SystemdCgroup = true"

    - name: Enable the containerd service and start service
      systemd:
        name: containerd
        state: restarted
        enabled: yes
        daemon-reload: yes

    - name: Install Kubernetes Components
      apt:
        name:
          - "kubelet={{ kubernetes_release }}"
          - "kubeadm={{ kubernetes_release }}"
        state: present
        update_cache: yes

    - name: Prevent Automatic Kubernetes Upgrades
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - containerd.io

    - name: Enable the Kubelet service
      service:
        name: kubelet
        enabled: yes

    - name: Load br_netfilter kernel module
      modprobe:
        name: br_netfilter
        state: present

    - name: Load overlay kernel module
      modprobe:
        name: overlay
        state: present

    - name: Set bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1

    - name: Set ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1

    - name: Reboot
      reboot:

- hosts: pd-k8s-control-1
  become: yes
  vars:
    kubernetes_major_version: "1.32"
    kubernetes_release: "1.32.2-1.1"

  tasks:

    - name: Install Kubectl
      apt:
        name: kubectl={{ kubernetes_release }}
        state: present
        force: yes

    - name: Prevent Automatic Kubernetes Upgrades
      dpkg_selections:
        name: kubectl
        selection: hold
