tcp_ports:
  - 22 # SSH
  - 2379:2380 # etcd
  - 6443 # Kubernetes API Server
  - 10250 # Kubelet Metrics
  - 30000:32767 # NodePort Services
  - 179 # BGP
  - 53 # DNS
  - 7946
  - 6789
  - 443
  - 80
  - 8472 # Flannel
  - 8285 # Flannel
  - 9100 # prometheus-node-exporter
  - 10257
  - 2381
  - 10259
  - 10249

udp_ports:
  - 53 # DNS
  - 7946
  - 6789
  - 8285 # Flannel
  - 8472 # Flannel
  - 9100 # prometheus-node-exporter