tcp_ports:
  - 22 # SSH
  - 2379:2380 # etcd
  - 6443 # Kubernetes API Server
  - 10250 # Kubelet Metrics
  - 30000:32767 # NodePort Services
  - 179 # BGP
  - 53 # DNS
  - 7946
  - 6789

udp_ports:
  - 53 # DNS
  - 7946
  - 6789