- name: Manage UFW firewall rules related to k3s cluster
  hosts: pd-k8s
  become: true
  vars_files:
    - ports.yml
  gather_facts: False

  tasks:
  
    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ tcp_ports }}"
      when: tcp_ports is defined

    - community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      loop: "{{ udp_ports }}"
      when: udp_ports is defined