- name: Label worker nodes
  hosts: pd-k8s-workers
  become: yes

  tasks:

    - name: Apply worker label
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/ansible/.kube/config label nodes pd-k8s-worker-1 role=worker
        kubectl --kubeconfig=/home/ansible/.kube/config label nodes pd-k8s-worker-2 role=worker
        kubectl --kubeconfig=/home/ansible/.kube/config label nodes pd-k8s-worker-3 role=worker
      register: res
      changed_when: res.rc != 0