---
- name: Disable password-based SSH access and enable public key authentication
  hosts: pd-k8s-workers
  become: true
  gather_facts: False

  tasks:

    - name: Ensure nfs-common is installed
      apt:
        name: nfs-common 
        state: present

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /mnt/pihole
        state: directory
        mode: '0755'

    - name: Mount NFS volumes
      ansible.posix.mount:
        src: 192.168.100.17:/mnt/Volume-01/pihole
        path: /mnt/pihole
        opts: rw
        state: mounted
        fstype: nfs

- name: Deploy Truenas Volume
  hosts: k8s-proxy
  become: yes

  tasks:

    - name: Copy volume.yml to k8s-proxy
      copy:
        src: volume.yml
        dest: /opt/application_manifests/pihole/volume.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Create a volume from K8S YAML File
      kubernetes.core.k8s:
        state: present
        src: /opt/application_manifests/pihole/volume.yml
        kubeconfig: /home/ansible/.kube/config
      register: result

    - name: Write deployment result to a log file
      copy:
        content: "{{ result | to_nice_json }}"
        dest: "/var/log/pihole-volume-deploy.log"