- name: Deploy Truenas Volume
  hosts: k8s-proxy
  become: yes

  tasks:

    - name: Copy volume.yml to k8s-proxy
      copy:
        src: volume.yml
        dest: /opt/application_manifests/pihole/volume.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Create a volume from K8S YAML File
      kubernetes.core.k8s:
        state: present
        src: /opt/application_manifests/pihole/volume.yml
        kubeconfig: /home/ansible/.kube/config
      register: result

    - name: Write deployment result to a log file
      copy:
        content: "{{ result | to_nice_json }}"
        dest: "/var/log/pihole-volume-deploy.log"