---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    type: "local"
spec:
  storageClassName: "nfs"
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pihole
  name: "pihole-pvc"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---