- name: Deploy application
  hosts: k8s-proxy
  become: yes

  tasks:

    - name: Copy metallb.yml to k8s-proxy
      copy:
        src: metallb.yml
        dest: /opt/application_manifests/metallb.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Install
      ansible.builtin.shell: |
        kubectl apply --kubeconfig=/home/ansible/.kube/config -f https://raw.githubusercontent.com/metallb/metallb/main/config/manifests/metallb-native.yaml
      register: res
      changed_when: res.rc != 0

    - name: Install
      ansible.builtin.shell: |
        kubectl delete validatingwebhookconfiguration metallb-webhook-configuration

    - name: Create a metallb from K8S YAML File
      kubernetes.core.k8s:
        state: present
        src: /opt/application_manifests/metallb.yml
        kubeconfig: /home/ansible/.kube/config
      register: result

    - name: Write deployment result to a log file
      copy:
        content: "{{ result | to_nice_json }}"
        dest: "/var/log/metallb-deploy.log"