- name: Install docker
  hosts: k8s-cluster-1
  become: yes

  tasks:

    - name: Updates
      apt:
        update_cache: yes

    - name: Disable SWAP
      shell: |
        swapoff -a

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # Forwarding of IPv4 traffic and allowing iptables to see bridged traffic is required. Execute the following commands to enable this:

    - name: Create empty file for containerd forwarding
      copy:
        content: ""
        dest: /etc/modules-load.d/k8s.conf
        force: no

    - name: Configure modules for containerd
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        block: |
          overlay
          br_netfilter

    - name: Create an empty file for K8S sysctl parameters
      copy:
        content: ""
        dest: /etc/sysctl.d/k8s.conf
        force: no

    - name: Configure sysctl parameters for IPv4 forwarding
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.ipv4.ip_forward                 = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"

    - name: Apply sysctl parameters
      command: sysctl --system

    # Docker Installation https://docs.docker.com/engine/install/debian/

    - name: Remove old version of docker
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: true

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
        state: present

    - name: Get DEB architecture
      shell: dpkg --print-architecture
      register: deb_architecture

    - name: Set default distribution values
      set_fact:
        distribution: "{{ ansible_distribution }}"
        distribution_release: "{{ ansible_distribution_release }}"
      when: distribution is not defined and distribution_release is not defined
    
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/{{ distribution | lower }} {{ distribution_release }} stable"
        state: present
        filename: docker

    - name: Updates
      apt:
        update_cache: yes

    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable service docker
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started
