---
# Run playbook as cvadmin using the below:
#
# ansible-playbook -i inventory/pd_debian/hosts.yml debian_playbooks/create_ansible_user.yml --ask-pass --ask-become-pass --vault-password-file /home/ansible/vault/ansible_user_pass_secret.txt

- name: Create a user with sudo privileges
  hosts: k8s-proxy
  become: yes
  gather_facts: false
  remote_user: cvadmin
  become: yes
  vars_files:
    - ansible_user_pass.yml
  vars:
    - ssh_key_file: "/home/{{ username }}/.ssh/id_rsa"
    - username: ansible
  tasks:

    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present

    - name: Install passlib using pip
      pip:
        name: passlib
        state: present
        executable: pip3
        extra_args: --break-system-packages

    - name: Create a new user
      user:
        name: "{{ username }}" 
        password: "{{ my_password | password_hash('sha512') }}" 
        shell: /bin/bash
        state: present
        
    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Allow passwordless sudo for the user (Debian/Ubuntu)
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ username }}'
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Ensure the .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Add SSH public key to authorized_keys on remote hosts
      authorized_key:
        user: "{{ username }}"
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present