---
- name: Configure Network, Hostname, and Nameserver
  hosts: netbox
  become: true
  gather_facts: False

  tasks:

    # Configure System Hostname

    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    # Set nameserver

    - name: Set nameserver or search domain
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.20.20.50" 
        line: "search cvlab.net" 

    # Configure interfaces

    - name: Configure network interfaces
      ansible.builtin.template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: '0644'
        backup: true
      notify: Restart networking

  handlers:

    - name: Restart networking
      ansible.builtin.service:
        name: networking
        state: restarted
