#
#
# ansible-playbook -i inventory/pd_debian/hosts.yml debian_playbooks/debian_base_config.yml
---
- name: Disable password-based SSH access and enable public key authentication
  hosts: pd-k8s
  become: true
  gather_facts: False

  tasks:

    # Mount NFS Share

    - name: Ensure nfs-common is installed
      apt:
        name: nfs-common 
        state: present

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /mnt/truenas
        state: directory
        mode: '0755'

    - name: Mount NFS volumes
      ansible.posix.mount:
        src: 192.168.100.17:/mnt/Volume-01/Docker
        path: /mnt/truenas
        opts: rw
        state: mounted
        fstype: nfs

    # Configure System Hostname

    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname}}"

    # Set nameserver

    - name: Set nameserver or search domain
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
       # line: "nameserver 10.20.20.10" 
        line: "search cv-labs.net" 