---
# This playbook disables password authentication for user ansible
# !!!! Fix playbook to disable ssh for only the user ansible !!!!
# ansible-playbook -i inventory/pd_debian/hosts.yml debian_playbooks/disable_ansible_pw.yml

- name: Disable password-based SSH access and enable public key authentication
  hosts: all
  become: true

  tasks:

    - name: Add Match block to sshd_config for ansible user
      blockinfile:
        path: /etc/ssh/sshd_config
        marker: "# BEGIN ansible settings"
        block: |
          Match User ansible
            PasswordAuthentication no

    - name: Restart SSH service to apply changes
      service:
        name: ssh
        state: restarted
