---
# This playbook disables password authentication for user ansible
# !!!! Fix playbook to disable ssh for only the user ansible !!!!
# ansible-playbook -i inventory/pd_debian/hosts.yml debian_playbooks/disable_ansible_pw.yml

- name: Disable password-based SSH access and enable public key authentication
  hosts: all
  become: true

  tasks:

    - name: Ensure PasswordAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Ensure PubkeyAuthentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Ensure ChallengeResponseAuthentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
        state: present

    - name: Ensure UsePAM is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UsePAM'
        line: 'UsePAM no'
        state: present

    - name: Restart SSH service to apply changes
      service:
        name: ssh
        state: restarted
