- name: Disable password-based SSH access and enable public key authentication
  hosts: all
  become: true
  gather_facts: False

  tasks:

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /mnt/truenas
        state: directory
        mode: '0755'

    - name: Mount NFS volumes with noauto according to boot option
      ansible.posix.mount:
        src: 192.168.100.17:/mnt/Volume-01/Docker
        path: /mnt/truenas
        opts: defaults,0,0
        state: mounted
        fstype: nfs