services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    networks:
      media_network:
        ipv4_address: 172.20.0.5
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    # Uncomment the devices section for tv tuners and intel gpus
    #devices:
      #- /dev/dvb:/dev/dvb # Uncomment this device for typical USB TV Tuner cards
      #- /dev/dri:/dev/dri # Uncomment this to use intel GPUs for Hardware Transcoding
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PLEX_CLAIM=claim-TTyAXcNFo43Yth38kApb
      # Uncomment the lines below to use Nvidia GPUs for Hardware Transcoding
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /data/plex-data:/config # Plex server application data is stored in a folder called 'plexmediaserver' in the same directory as the docker-compose.yaml file
      - /mnt/truenas/media/sonarr/tv:/mnt/tv
      - /mnt/truenas/media/radarr/movies:/mnt/movies
    restart: unless-stopped
    # Uncomment the lines below to use Nvidia GPUs for Hardware Transcoding
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYzJkNmNmYzlkZDk0MjljYmQyZjIxYTM1YTI3NTliOWEiLCJ0IjoiNWJkZmFhOWMtZDE2Mi00NzBhLWE0NDctNGIwODE2MjE2ZTc3IiwicyI6Ik1qY3hPVFZtWlRBdE1Ua3pNUzAwTldZeExUaG1NVFF0TjJaaE9EQTBaREExWVRjMSJ9
    networks:
      media_network:
        ipv4_address: 172.20.0.6
        
networks:
  media_network:
    external: true