services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000 # User ID
      - PGID=1000 # Group ID
      - TZ=America/New_York # Your timezone
    volumes:
      - /data/sonarr-data:/config
      - /mnt/truenas/media/sonarr/tv:/tv
      - /mnt/truenas/media/downloads:/downloads
    ports:
      - 8989:8989 # sonarr web UI port
    restart: unless-stopped