---
all:
  hosts:
    Debian12_Template:
      ansible_host: 10.20.20.2
    docker1:
      ansible_host: 10.20.20.10
    docker1-dev:
      ansible_host: 10.20.20.110
    gitlab:
      ansible_host: 10.20.20.11
    ansible:
      ansible_host: 10.20.20.12
docker:
  hosts:
    docker1:
    docker1-dev: