---
all:
  hosts:
    Debian12_Template:
      ansible_host: 10.20.20.2
    docker1:
      ansible_host: 10.20.20.10
    docker1-dev:
      ansible_host: 10.20.20.110
    gitlab:
      ansible_host: 10.20.20.11
    ansible:
      ansible_host: 10.20.20.12
    k8s-proxy:
      ansible_host: 10.20.20.13
    pd-k8s-control-1:
      ansible_host: 10.30.30.10
    pd-k8s-worker-1:
      ansible_host: 10.30.30.11
    pd-k8s-worker-2: 
      ansible_host: 10.30.30.12
    pd-k8s-worker-3:
      ansible_host: 10.30.30.13
docker:
  hosts:
    docker1:
    docker1-dev:
pd-k8s:
  hosts:
    pd-k8s-control-1:
    pd-k8s-worker-1:
    pd-k8s-worker-2:
    pd-k8s-worker-3:
pd-k8s-workers:
  hosts:
    pd-k8s-worker-1:
    pd-k8s-worker-2:
    pd-k8s-worker-3: