services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000 # User ID
      - PGID=1000 # Group ID
      - TZ=America/New_York # Your timezone
    volumes:
      - /data/nzbget-data:/config
      - /mnt/truenas/media/radarr/movies:/movies
      - /mnt/truenas/media/sonarr/tv:/tv
      - /mnt/truenas/media/downloads:/downloads
    ports:
      - 6789:6789 # nzbget web UI port
    restart: unless-stopped