services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000 # User ID
      - PGID=1000 # Group ID
      - TZ=America/New_York # Your timezone
    volumes:
      - /data/radarr-data:/config
      - /mnt/truenas/media/radarr/movies:/movies
      - /mnt/truenas/media/downloads:/downloads
    ports:
      - 7878:7878 # radarr web UI port
    restart: unless-stopped
    networks:
      media_network:
        ipv4_address: 172.20.0.3

networks:
  media_network:
    external: true