
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "America/New_York"
      FTLCONF_webserver_api_password: "SeaBass7!"
      # Other optional environment variables can be added here, e.g.,
      # DNS_SERVERS: "1.1.1.1;1.0.0.1"
      # FTLCONF_DNS_LISTEN_INTERFACE: "eth0"
    volumes:
      - "/data/pihole-data/config:/etc/pihole"
      - "/data/pihole/data/etc-dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN # Required for DHCP server if enabled
    restart: unless-stopped
    networks:
      services_network:
        ipv4_address: 172.20.0.18

networks:
  services_network:
    external: true