- name: Disable password-based SSH access and enable public key authentication
  hosts: pd-k3s
  become: true
  gather_facts: False

  tasks:

    # Mount NFS Share

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ tcp_ports }}"

    - community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      loop: "{{ udp_ports }}"