---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 65099
      peer-asn: 65012
      peer-address: 192.168.100.1
    address-pools:
    - name: metallb-vip-space
      protocol: bgp
      addresses:
      - 192.150.1.0/24
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
        communities:
        - 64512:1234  
---  
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  creationTimestamp: null
  name: peer1
  namespace: metallb-system
spec:
  myASN: 65099
  peerASN: 65012
  peerAddress: 192.168.100.1
status: {}
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  creationTimestamp: null
  name: bgpadvertisement1
  namespace: metallb-system
spec:
  aggregationLength: 32
  communities:
  - 64512:1234
  ipAddressPools:
  - vip-ip-space
  localPref: 100
status: {}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  creationTimestamp: null
  name: vip-ip-space
  namespace: metallb-system
spec:
  addresses:
  - 192.168.175.1-192.168.175.150
status: {}
