services:
    authentik_ldap:
        image: ghcr.io/goauthentik/ldap:2025.6.4
        container_name: authentik-ldap-outpost
        networks:
           - authentik_network
        ports:
            - 389:3389
            - 636:6636
        environment:
            AUTHENTIK_HOST: https://authentik.cvlab.net
            AUTHENTIK_INSECURE: "true"
            AUTHENTIK_TOKEN: R8OFbseaTKEQ7zMyVMftF1hFzaA7v9aBRcGu946Q54lLzHvlGIG9DyptsK62

networks:
  authentik_network:
    external: true
