---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-pv"
  labels:
    type: "local"
spec:
  storageClassName: "nfs"
  capacity:
    storage: "5000Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media"
  name: "media-pvc"
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5000Gi"
---
