- name: Deploy nzbget
  hosts: k8s-proxy
  become: yes

  tasks:

    - name: Copy nzbget.yml to k8s-proxy
      copy:
        src: nzbget.yml
        dest: /opt/application_manifests/nzbget.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Copy kustomization.yml to k8s-proxy
      copy:
        src: kustomization.yml
        dest: /opt/application_manifests/kustomization.yml
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Install nzbget
      ansible.builtin.shell: |
        kubectl apply --kubeconfig=/home/ansible/.kube/config -k /opt/application_manifests/kustomization.yml
      register: res
      changed_when: res.rc != 0