---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget-deployment
  namespace: media
  labels:
    app: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: docker.io/linuxserver/nzbget:amd64-latest
        ports:
        - containerPort: 6789
        volumeMounts:
        - mountPath: /config
          subPath: configs/nzbget-data
          name: media-pv
        - mountPath: /downloads
          subPath: downloads
          name: media-pv
      volumes:
      - name: media-pv
        persistentVolumeClaim:
          claimName: media-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nzbget-service
  namespace: media
spec:
  selector:
    app: nzbget
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6789
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget-ingress
  namespace: media
spec:
  rules:
  - host: nzbget.cv-labs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget-service
            port:
              number: 80